export interface LutPreset {
  id: string;
  name: string;
  description: string;
  cubeText: string;
  sourceName?: string;
  sourceUrl?: string;
  license?: string;
  swatch: [string, string, string];
}

type Transform = (r: number, g: number, b: number) => [number, number, number];

const clamp01 = (value: number) => Math.max(0, Math.min(1, value));

const mix = (a: number, b: number, t: number) => a + (b - a) * t;

function contrast(value: number, amount: number) {
  return clamp01((value - 0.5) * amount + 0.5);
}

function vibrance(r: number, g: number, b: number, amount: number): [number, number, number] {
  const max = Math.max(r, g, b);
  const avg = (r + g + b) / 3;
  const boost = (max - avg) * -amount;
  return [
    clamp01(r + (max - r) * boost),
    clamp01(g + (max - g) * boost),
    clamp01(b + (max - b) * boost),
  ];
}

export function createPresetCubeText(title: string, size: number, transform: Transform): string {
  const lines = [
    `TITLE "${title.replace(/"/g, '')}"`,
    `LUT_3D_SIZE ${size}`,
    'DOMAIN_MIN 0 0 0',
    'DOMAIN_MAX 1 1 1',
  ];
  for (let b = 0; b < size; b++) {
    for (let g = 0; g < size; g++) {
      for (let r = 0; r < size; r++) {
        const rgb = transform(r / (size - 1), g / (size - 1), b / (size - 1)).map(clamp01);
        lines.push(rgb.map((value) => value.toFixed(6)).join(' '));
      }
    }
  }
  return `${lines.join('\n')}\n`;
}

const SIZE = 17;

export const LUT_PRESETS: LutPreset[] = [
  {
    id: 'cinematic-teal-orange',
    name: '电影青橙',
    description: '压暗蓝绿阴影，提暖肤色高光。',
    swatch: ['#12313a', '#d69048', '#f7c27a'],
    cubeText: createPresetCubeText('T8 Cinematic Teal Orange', SIZE, (r, g, b) => {
      const luma = r * 0.2126 + g * 0.7152 + b * 0.0722;
      const shadow = 1 - luma;
      const highlight = luma;
      let nr = contrast(r, 1.08);
      let ng = contrast(g, 1.04);
      let nb = contrast(b, 1.1);
      nr = clamp01(nr + highlight * 0.08 - shadow * 0.02);
      ng = clamp01(ng + shadow * 0.055);
      nb = clamp01(nb + shadow * 0.1 - highlight * 0.055);
      return vibrance(nr, ng, nb, 0.18);
    }),
  },
  {
    id: 'soft-film-warm',
    name: '柔和暖胶片',
    description: '降低硬对比，暖化高光，适合人像。',
    swatch: ['#3d332c', '#b98259', '#ffd8a6'],
    cubeText: createPresetCubeText('T8 Soft Warm Film', SIZE, (r, g, b) => {
      const nr = mix(r, contrast(r, 0.9), 0.65) + 0.035;
      const ng = mix(g, contrast(g, 0.92), 0.55) + 0.015;
      const nb = mix(b, contrast(b, 0.88), 0.65) - 0.025;
      return [nr, ng, nb].map(clamp01) as [number, number, number];
    }),
  },
  {
    id: 'clean-commercial',
    name: '清透商业',
    description: '轻微提亮和加饱和，适合商品图。',
    swatch: ['#164e63', '#22c55e', '#f8fafc'],
    cubeText: createPresetCubeText('T8 Clean Commercial', SIZE, (r, g, b) => {
      const [vr, vg, vb] = vibrance(r, g, b, 0.22);
      return [
        clamp01(contrast(vr, 1.06) + 0.025),
        clamp01(contrast(vg, 1.04) + 0.02),
        clamp01(contrast(vb, 1.03) + 0.015),
      ];
    }),
  },
  {
    id: 'noir-fade',
    name: '冷调褪色',
    description: '低饱和、轻冷色，适合氛围图。',
    swatch: ['#111827', '#64748b', '#cbd5e1'],
    cubeText: createPresetCubeText('T8 Noir Fade', SIZE, (r, g, b) => {
      const gray = r * 0.299 + g * 0.587 + b * 0.114;
      return [
        clamp01(mix(gray, r, 0.42) * 0.92 + 0.035),
        clamp01(mix(gray, g, 0.46) * 0.95 + 0.035),
        clamp01(mix(gray, b, 0.5) * 1.04 + 0.045),
      ];
    }),
  },
  // External inspiration/source: YahiaAngelo/Film-Luts
  // License: MIT (repo README/license). Keep this attribution when extending these presets.
  // The bundled cubeText below is generated by this project and style-inspired; it does not copy raw .cube files.
  // URL: https://github.com/YahiaAngelo/Film-Luts
  {
    id: 'film-luts-kodak-2383',
    name: 'Film LUTs · Kodak 2383',
    description: '免费 Film-Luts 项目风格参考：暖高光、胶片密度。',
    sourceName: 'YahiaAngelo/Film-Luts',
    sourceUrl: 'https://github.com/YahiaAngelo/Film-Luts',
    license: 'MIT',
    swatch: ['#1f2933', '#8f5d38', '#f4c27a'],
    cubeText: createPresetCubeText('Film-Luts Inspired Kodak 2383', SIZE, (r, g, b) => {
      const luma = r * 0.299 + g * 0.587 + b * 0.114;
      return [
        clamp01(contrast(r, 1.12) + luma * 0.045),
        clamp01(contrast(g, 1.06) + luma * 0.018),
        clamp01(contrast(b, 1.02) - luma * 0.055),
      ];
    }),
  },
  {
    id: 'film-luts-fuji-soft',
    name: 'Film LUTs · Fuji Soft',
    description: '免费 Film-Luts 项目风格参考：柔绿阴影、干净肤色。',
    sourceName: 'YahiaAngelo/Film-Luts',
    sourceUrl: 'https://github.com/YahiaAngelo/Film-Luts',
    license: 'MIT',
    swatch: ['#18332f', '#7e9f78', '#f5c99b'],
    cubeText: createPresetCubeText('Film-Luts Inspired Fuji Soft', SIZE, (r, g, b) => {
      const [vr, vg, vb] = vibrance(r, g, b, 0.15);
      const luma = r * 0.299 + g * 0.587 + b * 0.114;
      return [
        clamp01(contrast(vr, 0.98) + luma * 0.02),
        clamp01(contrast(vg, 1.02) + (1 - luma) * 0.04),
        clamp01(contrast(vb, 0.96) - (1 - luma) * 0.025),
      ];
    }),
  },
];

export function getLutPreset(id?: string | null): LutPreset {
  return LUT_PRESETS.find((preset) => preset.id === id) || LUT_PRESETS[0];
}
